name: lint, test, build
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  my-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci
      - name: build project for production
        run: npm run build:prod
        if: always()
      - name: lint typescript
        if: always()
        run: npm run lint
      - name: lint styles
        if: always()
        run: npm run stylelint
      - name: unit tests
        if: always()
        run: npm run test:unit
      